image: ruby:latest

before_script:
- gem install jekyll
- gem install jekyll-asciidoc

test:
  stage: test
  script:
  - jekyll build -d test
  artifacts:
    paths:
    - test
  except:
  - master

pages:
  stage: deploy
  script:
  - jekyll build -d public
  artifacts:
    paths:
    - public
  only:
  - master
